import { type Word } from './cardDeckTypes';

/**
 * TODO remove.
 */
export const mockDeck: Word[] = [
	{
		id: 'word_noun_chien',
		frenchWord: 'chien',
		englishWords: ['dog'],
		isVulgar: false,
		lemmaId: 'chien',
		frenchArticle: 'le',
		englishArticle: 'The',
		partOfSpeech: 'noun',
		CEFR: 'A1',
		gender: 'Masculine',
		pronunciation: 'luh shee-ehn',
		correctCount: 14,
	},
	{
		id: 'word_noun_maison',
		frenchWord: 'maison',
		englishWords: ['house'],
		isVulgar: false,
		lemmaId: 'maison',
		frenchArticle: 'la',
		englishArticle: 'The',
		partOfSpeech: 'noun',
		CEFR: 'A1',
		gender: 'Feminine',
		pronunciation: 'lah meh-zohn',
		correctCount: 14,
	},
	{
		id: 'word_noun_livre',
		frenchWord: 'livre',
		englishWords: ['book'],
		isVulgar: false,
		lemmaId: 'livre',
		frenchArticle: 'le',
		englishArticle: 'The',
		partOfSpeech: 'noun',
		CEFR: 'A1',
		gender: 'Masculine',
		pronunciation: 'luh leev-uh',
		correctCount: 7,
	},
	{
		id: 'word_noun_pomme',
		frenchWord: 'pomme',
		englishWords: ['apple'],
		isVulgar: false,
		lemmaId: 'pomme',
		frenchArticle: 'la',
		englishArticle: 'The',
		partOfSpeech: 'noun',
		CEFR: 'A1',
		gender: 'Feminine',
		pronunciation: 'lah pom',
		correctCount: 11,
	},
];
