import { type Word } from './cardDeckTypes';

/**
 * TODO remove.
 */
export const mockDeck: Word[] = [
	{
		id: 'word_noun_chien',
		frenchWord: 'chien',
		englishWord: 'dog',
		isVulgar: false,
		lemmaId: 'chien',
		frenchArticle: 'le',
		englishArticle: 'The',
		partOfSpeech: 'noun',
		CEFR: 'A1',
		gender: 'Masculine',
		pronunciation: 'luh shee-ehn',
		userScore: 14,
	},
	{
		id: 'word_noun_maison',
		frenchWord: 'maison',
		englishWord: 'house',
		isVulgar: false,
		lemmaId: 'maison',
		frenchArticle: 'la',
		englishArticle: 'The',
		partOfSpeech: 'noun',
		CEFR: 'A1',
		gender: 'Feminine',
		pronunciation: 'lah meh-zohn',
		userScore: 14,
	},
	{
		id: 'word_noun_livre',
		frenchWord: 'livre',
		englishWord: 'book',
		isVulgar: false,
		lemmaId: 'livre',
		frenchArticle: 'le',
		englishArticle: 'The',
		partOfSpeech: 'noun',
		CEFR: 'A1',
		gender: 'Masculine',
		pronunciation: 'luh leev-uh',
		userScore: 7,
	},
	{
		id: 'word_noun_pomme',
		frenchWord: 'pomme',
		englishWord: 'apple',
		isVulgar: false,
		lemmaId: 'pomme',
		frenchArticle: 'la',
		englishArticle: 'The',
		partOfSpeech: 'noun',
		CEFR: 'A1',
		gender: 'Feminine',
		pronunciation: 'lah pom',
		userScore: 11,
	},
];
